title: My website
author: Sanjay K V
email: sanjay@recodehive.com
description: > # this means to ignore newlines until "baseurl:"
  This is going to be cool.

# social links
twitter_username: sanjay_kv # DO NOT include the @ character, or else the build will fail!
github_username:  sanjay-kv # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
